#!/bin/bash
apt-get update && apt-get upgrade -y
apt-get install traceroute -y
apt-get install iperf3 -y
echo "sudo su -" > /home/ubuntu/.bash_history
echo "alias t='traceroute -n'" >> /home/ubuntu/.bashrc
echo "alias p=ping" >> /home/ubuntu/.bashrc
chown ubuntu /home/ubuntu/.bash_history
chown ubuntu /home/ubuntu/.bashrc
echo "alias t='traceroute -n'" >> /root/.bashrc
echo "alias p=ping" >> /root/.bashrc
