#!/bin/bash
apt-get update && apt-get upgrade -y
apt-get install traceroute -y
apt-get install iperf3 -y
echo "sudo su -" > /home/ubuntu/.bash_history
echo "iperf3 -V -p 8000 -P 32 -i 5 -t 30 -c 10." >> /home/ubuntu/.bash_history
chown ubuntu /home/ubuntu/.bash_history
echo "iperf3 -V -p 8000 -P 32 -i 5 -t 30 -c 10." > /root/.bash_history
